### ISSUE TITLE
Bad PostCSS support

### ISSUE THREAD

**Issue by ai** [raulghm/social-media-colors#3]
PostCSS has no build-in W3C CSS variables. It is just a optional plugin. Many of users use [postcss-simple-vars](https://github.com/postcss/postcss-simple-vars). `postcss-import` is optional plugin too.

Anyway providing CSS file to import is not a PostCSS way. It is preprocessor way.

Like [postcss-brand-colors](https://github.com/postcss/postcss-brand-colors) you should provide plugin to transform custom syntax.

**Comment by raulghm** [comment]
No, this is a way of support for PostCSS, maybe I should give a better explanation, but I do not think it's a bad support.

**Comment by ai** [comment]
PostCSS is not a preprocessor ;). I know that is dard but you need to rethink CSS processing, when you move to PostCSS.

**Comment by ai** [comment]
I am saying that it is a bad PostCSS API as author of PostCSS ;)

**Comment by raulghm** [comment]
Sorry, PostCSS is not a preprocessor and thank for your comments ;)
